SET NAMES utf8mb4;
CREATE TABLE IF NOT EXISTS erp_snapshots (
  state_key VARCHAR(64) PRIMARY KEY,
  payload_json LONGTEXT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS raw_batches_qc (
  batch_id VARCHAR(64) PRIMARY KEY,
  supplier VARCHAR(120) NOT NULL,
  category VARCHAR(32) NOT NULL,
  qty DECIMAL(10,2) NOT NULL,
  fat_pct DECIMAL(5,2) DEFAULT 0,
  prot_pct DECIMAL(5,2) DEFAULT 0,
  ph_val DECIMAL(4,2) DEFAULT 6.70,
  water_pct DECIMAL(5,2) DEFAULT 0,
  verdict VARCHAR(20) DEFAULT 'PASSED',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS stock_movements (
  id INT AUTO_INCREMENT PRIMARY KEY,
  batch_code VARCHAR(64) NOT NULL,
  plu VARCHAR(20) NOT NULL,
  from_loc VARCHAR(60) NOT NULL,
  to_loc VARCHAR(60) NOT NULL,
  qty DECIMAL(10,2) NOT NULL,
  moved_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS customer_orders (
  order_id INT AUTO_INCREMENT PRIMARY KEY,
  source VARCHAR(32) NOT NULL,
  apt VARCHAR(32) NOT NULL,
  phone VARCHAR(32) NOT NULL,
  slot VARCHAR(32) NOT NULL,
  total_kzt INT NOT NULL,
  items_json TEXT NOT NULL,
  status VARCHAR(24) DEFAULT 'NEW',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
